version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Building project..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
