version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Dependencies..."
      - npm install

  build:
    commands:
      - echo "Building The Project..."
      - npm run build

artifacts:
  files:
    - dist/**/* # събраният JS код
    - package.json
    - package-lock.json
